server:
  port: 8081
spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/deploy_demo?useUnicode=true&characterEncoding=utf8
    password: 1234
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka